/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateTableImport } from './routes/create-table'
import { Route as IndexImport } from './routes/index'
import { Route as TableTableImport } from './routes/table/$table'

// Create/Update Routes

const CreateTableRoute = CreateTableImport.update({
  id: '/create-table',
  path: '/create-table',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TableTableRoute = TableTableImport.update({
  id: '/table/$table',
  path: '/table/$table',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-table': {
      id: '/create-table'
      path: '/create-table'
      fullPath: '/create-table'
      preLoaderRoute: typeof CreateTableImport
      parentRoute: typeof rootRoute
    }
    '/table/$table': {
      id: '/table/$table'
      path: '/table/$table'
      fullPath: '/table/$table'
      preLoaderRoute: typeof TableTableImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-table': typeof CreateTableRoute
  '/table/$table': typeof TableTableRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-table': typeof CreateTableRoute
  '/table/$table': typeof TableTableRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-table': typeof CreateTableRoute
  '/table/$table': typeof TableTableRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-table' | '/table/$table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-table' | '/table/$table'
  id: '__root__' | '/' | '/create-table' | '/table/$table'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTableRoute: typeof CreateTableRoute
  TableTableRoute: typeof TableTableRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTableRoute: CreateTableRoute,
  TableTableRoute: TableTableRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-table",
        "/table/$table"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-table": {
      "filePath": "create-table.tsx"
    },
    "/table/$table": {
      "filePath": "table/$table.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
